# Generated by Django 4.0.1 on 2022-01-18 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='uid',
            new_name='uuid',
        ),
    ]
